name: Rust Build and Clippy Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v3
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install libssl-dev openssl -y

      - name: Early Build
        run: cargo build --workspace --tests

      - name: Check Rust Code Format
        run:  cargo fmt -- --check

      - name: Run Rust Clippy
        run: cargo clippy --all-targets -- -D warnings
